Sinatra assignment
ymoto9915/memoapp pull request #1
Opened 2019-01-31 11:44 UTC by ymoto9915

Sinatraの課題です。ご確認をお願いします。

2019-02-01 07:53 UTC, komagata requested changes

2019-02-01 07:53 UTC, komagata commented on Gemfile
> +# gem "rails"
必要無い行は削除してくださいー

2019-02-01 07:53 UTC, komagata commented on app.rb
> +patch "/patch/:id" do
`PATCH /patch/123`だと冗長なのでRESTのプラクティスを参考にシンプルなURL設計を再考してみてください。

2019-02-05 12:36 UTC, ymoto9915 commented on app.rb
> +patch "/patch/:id" do
レビューありがとうございます。RESTについて調べました。PATCH以外にも`show /show/123`、`delete /delete/123`なども変更すべきでしょうか？

2019-02-06 08:31 UTC, ymoto9915 commented on app.rb
> +patch "/patch/:id" do
URLをシンプルにし、必要のない行を削除しました。

2019-02-07 05:35 UTC, merged